services:
  oscars_overview_app:
    container_name: oscars_overview_app
    build:
      context: .
    volumes:
      - ./app/src:/var/www/html/src
      - ./app/includes:/var/www/html/includes
    ports:
      - "80:80"
